# Generated by Django 6.0.6 on 2026-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
