# Generated by Django 6.0.6 on 2026-08-01 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee Bill/Payment', 'verbose_name_plural': 'Fee Bills/Payments'},
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together={('student', 'fee_structure')},
        ),
        migrations.AddField(
            model_name='feepayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What student should pay', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='control_number',
            field=models.CharField(blank=True, db_index=True, help_text='From NMB/GePG', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='control_number_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('nmb', 'NMB Bank'), ('gepg', 'GePG'), ('selcom', 'Selcom')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='invoice_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='Bank ref from NMB report', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(blank=True, help_text='Last date to pay without penalty', null=True),
        ),
        migrations.AddField(
            model_name='otherpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Mobile', 'Mobile Money'), ('Control', 'Control Number')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Mobile', 'Mobile Money'), ('Control', 'Control Number')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feestructure'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Mobile', 'Mobile Money'), ('Control', 'Control Number')], default='Control', max_length=20),
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='amount',
        ),
    ]
