# Generated by Django 6.0.6 on 2026-08-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_feepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Copied from FeeStructure on creation', null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
