# Generated by Django 6.0.6 on 2026-08-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_nmbimportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nmbimportlog',
            options={'ordering': ['-imported_at']},
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='control_number',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='nmb_control_number',
            field=models.CharField(blank=True, db_index=True, help_text='Real control number from NMB/GePG. Parents use this to pay', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='system_control_number',
            field=models.CharField(blank=True, db_index=True, help_text='Internal tracking number before NMB assigns one', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nmbimportlog',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
