# Generated by Django 6.0.6 on 2026-08-02 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_nmbimportlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='nmb_control_number',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='bank_control_number',
            field=models.CharField(blank=True, db_index=True, help_text='Real control number from Bank/GePG. Parents use this to pay', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='control_number_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('nmb', 'NMB Bank'), ('crdb', 'CRDB Bank'), ('gepg', 'GePG'), ('selcom', 'Selcom'), ('other', 'Other Bank')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='system_control_number',
            field=models.CharField(blank=True, db_index=True, help_text='Internal tracking number before bank assigns one', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='Bank ref from bank report', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BankImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('bank_source', models.CharField(choices=[('manual', 'Manual Entry'), ('nmb', 'NMB Bank'), ('crdb', 'CRDB Bank'), ('gepg', 'GePG'), ('selcom', 'Selcom'), ('other', 'Other Bank')], default='other', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('matched', models.IntegerField(default=0)),
                ('not_found', models.IntegerField(default=0)),
                ('duplicate', models.IntegerField(default=0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.DeleteModel(
            name='NMBImportLog',
        ),
    ]
