# Generated by Django 6.0.6 on 2026-08-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_feepayment_nmb_control_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('payment_received', 'Payment Received')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=20)),
                ('sent_to', models.CharField(help_text='Phone number', max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('fee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.feepayment')),
            ],
        ),
    ]
