# Generated by Django 6.0.6 on 2026-07-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_teacher_photo'),
        ('accounts', '0001_initial'),
        ('students', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.guardian'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.teacher'),
        ),
    ]
