# Generated by Django 6.0.6 on 2026-07-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BABY', 'Baby'), ('MIDDLE', 'Middle'), ('TOP', 'Top'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7')], max_length=10)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
            options={
                'ordering': ['level', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('minimum_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remark', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-minimum_mark'],
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('teacher_remark', models.TextField(blank=True)),
                ('head_teacher_remark', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['student__class_room', 'class_position'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['class_room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2'), ('TERM3', 'Term 3')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Mid Term'), ('TERMINAL', 'Terminal'), ('ANNUAL', 'Annual')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.classroom')),
            ],
            options={
                'ordering': ['term', 'class_room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('grade', models.CharField(blank=True, editable=False, max_length=2)),
                ('remark', models.CharField(blank=True, editable=False, max_length=100)),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.exam')),
            ],
            options={
                'ordering': ['student__class_room', 'subject', '-average_marks'],
            },
        ),
    ]
