# Generated by Django 6.0.6 on 2026-07-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='academics.exam'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='studentreport',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'class_room')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('level', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'name')},
        ),
    ]
