# Generated by Django 6.0.6 on 2026-07-07 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MIDTERM', 'Mid Term'), ('TERMINAL', 'Terminal'), ('MIDTERM', 'Mid Term'), ('ANNUAL', 'Annual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2'), ('TERM3', 'Term 3'), ('TERM3', 'Term 4')], max_length=10),
        ),
    ]
