# Generated by Django 6.0.6 on 2026-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentreport_academic_year_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2'), ('TERM3', 'Term 3'), ('TERM4', 'Term 4')], max_length=10),
        ),
    ]
