# Generated by Django 6.0.6 on 2026-07-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classroom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
