# Generated by Django 6.0.6 on 2026-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examresult_points_studentreport_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='division',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='division_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
